### ISSUE TITLE
配置文件中的数据路径不存在

### ISSUE THREAD

**Issue by agezhc** [CodingCat/xgboost4j-spark-scalability#6]
hi CodingCat，学习xgboost时找到了你的项目。研读了你的代码后，想尝试练下，发现配置中的数据不存在
/xgboost/dataset/transformed
/airline/raw/merged.csv
能否提供下，多谢啦
我的邮箱是 alexzhc@qq.com

**Comment by CodingCat** [comment]
we are using airline dataset which is easy to find

you are supposed to setup data path by your own
